### ISSUE TITLE
Incorrect display of dates in event

### ISSUE THREAD

**Issue by Chandraanshu** [CS2103AUG2016-T09-C3/main#119]
when event is created, the two dates displayed in the info bar are not correct. Also, the size of the task card is not big enough to display the dates

**Comment by Chandraanshu** [comment]
Also, taskcards are not coloured according to the task type

**Comment by cardboardcode** [comment]
But cannot resize the TaskListPanel. Too much debugging required.

**Comment by Chandraanshu** [comment]
Then can display the dates from the left so that they fit into the taskccard?

**Comment by cardboardcode** [comment]
The dates should fit regardless of placement. I will merge my branch to master tonight so you can have a look.
