### ISSUE TITLE
getFilteredTaskList should return first 6 tasks in the list.

### ISSUE THREAD

**Issue by cardboardcode** [CS2103AUG2016-T09-C3/main#24]
for now

**Comment by cardboardcode** [comment]
regarding the mysterious "personList" variable found in SceneBuilder, I have managed to locate where it originated from. 

It actually pertains to the getFilteredTaskList function because "personList" is a ObservableList<ReadOnlyTask> variable. It can be found on line 69 in TaskListPanel.java.

**Comment by cardboardcode** [comment]
taskListView <=> taskList

**Comment by chewwt** [comment]
actually just show the whole list if possible (for now). Implementation of filters for milestone v0.3?
